name: cruise-web

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main
    
    - name: NodeInstall
      run: sudo apt-get install nodejs
      
    # Build
    - name: Build
      run: yarn && yarn build

    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: build
        remote: /root/www/cruise-web/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        concurrency: 20
