name: cruise-web

on:
  push:
    branches: master

jobs:
  build-and-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    # Build
    - name: Build
      run: yarn build

    - name: Deploy
      uses: root
      with:
        local: build
        remote: /root/www/cruise-web/
